### ISSUE TITLE
This document needs renaming

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/charter#10]
I originally called this a *members' charter", but as @iteles has pointed out elsewhere,
https://github.com/foundersandcoders/charter/issues/9, I am confusing being a graduate of FAC and being a member--which is a longer term commitment that not everyone is going to be interested in or able to commit to.

I suggest that every occurrence of the word _member_ in the README is replaced by the word _graduate_ and that it be something that students will have to agree to from FAC7 onwards.

**Comment by NataliaLKB** [comment]
Will a separate membership's charter still be created? I do think one would be very beneficial.

**Comment by nelsonic** [comment]
Using the word "_graduate_" **_could**_ be misinterpreted as we _only_ accept applicants who have university degrees... which we are _hoping_ to move away from.
But, I cannot think of a better word...

**Comment by NataliaLKB** [comment]
We could just explicitly say **Founders & Coders' Graduate**

**Comment by iteles** [comment]
Alumni might work although not everyone knows what that is.

**Comment by nelsonic** [comment]
@NataliaLKB that would be _better_... however the word "graduate" still has a _specific_ meaning: https://en.wikipedia.org/wiki/Graduate

**Comment by sofer** [comment]
@NataliaLKB @iteles @nelsonic _"Students' charter"_?

**Comment by nelsonic** [comment]
_Students_ or ... [**_Initiates**_](http://starwars.wikia.com/wiki/Jedi_Initiate) ? :wink:

**Comment by rub1e** [comment]
Does it need an explanatory adjective at all? People will agree to this thing before they are students, initiates, graduates, or alumni.

So this could just be the **FAC Charter**

(The FAC pre-commit hook? Boom)

**Comment by iteles** [comment]
@rub1e With respect, I disagree because of #9 - What is a FAC member?  
In its current incarnation, it only applies to a subset of the people who interact with FAC which is less than ideal.

**Comment by rub1e** [comment]
@iteles yeah, fair enough - withdrawn

But I can't believe you "with-respected" me

**Comment by iteles** [comment]
@rub1e 😆 Doesn't it make you feel all grown up though? Ok, ok, let's take this side conversation out of the issue and into real life.

**Comment by sofer** [comment]
The title of the README has been reduced to _"Proposed conditions for being accepted onto FAC7"_, which works for me, so I am closing this issue now.
