### ISSUE TITLE
Does FAC/DWYL undercut this?

### ISSUE THREAD

**Issue by rub1e** [foundersandcoders/charter#11]
To what extent is this a worthwhile discussion to have before we have resolution on Ines and Nelson's plans? Should we put this in a drawer till then?

To be clear, I am bang up for a charter with proper rules and such, but so much of this is about employment that I wonder if it would be easier to make progress after DWYL is further along.

**Comment by iteles** [comment]
Good question @rub1e, https://github.com/foundersandcoders/charter/issues/2#issuecomment-145852699 :wink:

**Comment by sofer** [comment]
@rub1e given your the issue about timing #12 , I would not want to hold off too long, but with your question in mind, I have just moved the Charter proposal down the agenda for today's meeting.

**Comment by nelsonic** [comment]
@rub1e I'm curious as to your use of the work ["_undercut_"](https://en.wikipedia.org/wiki/Undercut) ... 

As far as we are concerned FAC _needs_ to have a Charter for _everyone_ involved to be _clear_ what the expectations are.

["_The Team_"](https://github.com/nelsonic/ateam) will do _everything_ to _support_ and _encourage_ people to continue contributing back to FAC's mission. Having people working _with_ "_The Team_" will mean FAC receives a steady _income_ so I don't see how it can "_undercut_" ...? (_sorry if I'm being a bit thick..._)

**Comment by sofer** [comment]
@rub1e two points:

1) The A-Team proposal https://github.com/nelsonic/ateam explicitly says that it does not cover students wanting to start their own project/adventure (with the support of their peers) or to work on freelance projects of their own accord, and I am very keen on an agreement or charter that covers all students;

2) I would not want students to get the idea that the existence of a commercial organisation in the space that is willing to provide yet more extraordinary support in helping them achieve their goals relieves them of collective responsibility and I also wound not want to heap all the responsibility for the sustainability of FAC onto the shoulders of just two people.

**Comment by rub1e** [comment]
@nelsonic - sorry, it was a bad word to use figuratively when in a financial context. I meant something more like supersede

@sofer agree
