### ISSUE TITLE
compulsory from 2016 onwards

### ISSUE THREAD

**Issue by rub1e** [foundersandcoders/charter#12]
Have we already accepted people for January? If so, I'm assuming we can't in all fairness ask them to sign up to this if they've already been told they've got a place? So does this meant the first cohort to be expected to agree to the charter is May 2016?

**Comment by iteles** [comment]
@rub1e Only conditional offers so far, so I think it's safe to assume that if they're warned in the next week of any changes (3 months in advance of the course starting mid January 2016), they've still received fair warning in time to change their plans (which were not concrete).

**Comment by nelsonic** [comment]
@rub1e agree that it would be _lame_ to change the "_Terms and Conditions_" for the course for people who have already been given places under the assumption that they don't have to "_give back_"... but as @iteles says, people have 3 months to change their minds if they think that the "_price_" they are being asked to "_pay_" is too high...

**Comment by rub1e** [comment]
Agreed
