### ISSUE TITLE
More detail regarding agency fees

### ISSUE THREAD

**Issue by thegsi** [foundersandcoders/charter#15]
'What is meant by an agency relationship? An agreement whereby FAC receives a fee from the employer.'
FAC could specify in more detail what this might mean in practice. Monthly or one off, how might this fee relate to salary, Some examples of past arrangements here would make the idea more comprehensible to potential FAC members.

**Comment by iteles** [comment]
@thegsi Typically in the world of 'recruitment agencies', this is a one-off lump sum. The industry standard is for it to be a percentage of the proposed first annual salary for the person being placed (and it's important to note here that this is a transaction between the employer and the _'agency'_ and does **not** come out of the person being placed's salary).

As an example, the latest relationships we have formed were a one-off 15% fee. This is at the lowest end of what is expected for agencies, particularly in London. The fees usually range from 15-25% and in some cases can hit 50% for hard to place positions.

**Comment by nelsonic** [comment]
@thegsi what Inês said. 
The main point is that it does not _cost_ the candidate _anything_ and has the potential to benefit FAC...

**Comment by thegsi** [comment]
Great, I just felt that a little more detail would put potential applicants as ease.
