### ISSUE TITLE
Possible 'game theory' thinking of member job seekers worried about increased competition

### ISSUE THREAD

**Issue by Joshua-Ronan-Phillips** [foundersandcoders/charter#16]
I'm a huge supporter of this agency model as I think it is a vital source of income for this amazing organisation!

My first thought was that graduate members looking for job might wonder if passing on the job role they find to FAC might open that job role up to the rest of the graduates and increase the competition for that role. I think this might just be something members will have to sacrifice to enjoy such an amazing free education, which I for one am happy to do. But I think we should think of ways to mitigate this worry people might have to increase the number of jobs people pass on to FAC and therefore increase FAC's ongoing funding. 

Possibly an open discussion of this problem with all members and how vital this form of funding is to the organisation will help in this area? I'd be interested on other peoples thoughts on this area.

Kindest of regards

JP

**Comment by sofer** [comment]
@Joshua-Ronan-Phillips this is a really good point. I think it would be entirely reasonable for that role not be advertised to other graduates until after a reasonable period had elapsed. 

At some point in the (possibly near) future, we hope to have a large enough backlog of projects and a large enough roster of employers that the need for students to go and find their own projects and their own employment opportunities may become moot, but in the meantime I really appreciate your feedback on how we can get through the next few months.

**Comment by hdrdavies** [comment]
I was wondering the same thing @Joshua-Ronan-Phillips :+1:
