### ISSUE TITLE
Overall Tone

### ISSUE THREAD

**Issue by msmichellegar** [foundersandcoders/charter#19]
I think the charter is really important, and I love the prospect of having more clarity around Founders and Coders membership. But I do think the tone of this document is a little negative overall. The language is quite cold and draconian. And although it makes very valid points, some of the wording sounds (unintentionally) controlling. I think this sort of tone breeds resentment and bad vibes, which obviously isn't what we're going for.

This is, I'm imagining, a document that will have to be read by all people thinking about applying to the course, or considering entering the Founders and Coders community. It's also a document that sets the tone for everyone in the existing community.

Given we have an interest in attracting productive new members to the cooperative, and in keeping the ones that we have, I think it might be worth making the document a little more welcoming. We're trying to encourage people to contribute to the community, after all. A few positive vibes wouldn't go astray. I get that this is a serious document outlining rules, but I think it's possible to lift up the language without sacrificing any key ideas from the charter.

I'm happy to put together a pull request with language suggestions, but will need another week or so to do this. Some things that could make a difference:
- A more inspiring introduction, describing some of the key values of FAC that lead us to conduct the community in this way (passion, kindness, knowledge-sharing, social justice)
- Fewer instances of cold legal terminology like "abide by", "failure to", "whereby", "terminate"

Thoughts?

**Comment by NataliaLKB** [comment]
:+1: completely agree @msmichellegar. On a (very) quick glance, the second draft: https://github.com/foundersandcoders/charter/pull/18 looks better. 

However I definitely think you should make a PR with some more uplifting and inspirational wording. FAC is a community and new people should come into it feeling welcomed and supported, not cautious/scared/controlled.

**Comment by minaorangina** [comment]
Agree with these points.  It's important to remember that future members of FAC will be brimming with enthusiasm when they walk through the door - we don't want to rain on the parade.  The charter can be both effective and welcoming in tone :smile: 

I'd also add that it's important to give all the aspects of the charter equal weighting and 'airtime'.  I know finances are a concern at this current time and, of course, a very important topic in general.  But we need to keep the charter balanced and independent of the transient concerns of today.

**Comment by NataliaLKB** [comment]
@minaorangina I couldn't agree more. :star: :+1:

**Comment by rub1e** [comment]
Totally see where you're coming from. Just to say that after #10, #9, #14 and others, #18 was rewritten so that's it's not at all a charter - it's more like Terms and Conditions. I do think a charter should be inspirational and welcoming, but I think stronger language is warranted when it comes to outlining people's responsibilities - formality is needed because it has become clear that we cannot merely rely on people's goodwill.

I want this document to be viewed as a contract, rather than a set of principles

**Comment by msmichellegar** [comment]
@rub1e As I said above, I think it's possible to achieve the same end without using such harsh and alienating language. I'm not suggesting we fall back to relying on "goodwill" or strip it down to mere principles, I just think this "contract" could be a tad more positive, especially if we're trying to inspire people to give back to the Founders and Coders community.

Personally, reading this document freaked me out a bit. That's not how I want newcomers to the community to feel.

**Comment by msmichellegar** [comment]
I also agree with @minaorangina:

_"I'd also add that it's important to give all the aspects of the charter equal weighting and 'airtime'. I know finances are a concern at this current time and, of course, a very important topic in general. But we need to keep the charter balanced and independent of the transient concerns of today."_

Like I said here https://github.com/foundersandcoders/charter/issues/20, I think if we're asking people to adhere to certain types of behaviour in a "contract", I think that should extend beyond just financial matters. This contract implies all we care about is conduct around employment. Which if that's the case, is kind of disappointing to me.

I feel like how people conduct themselves in the space and make other feel should also be important. If people follow all the financial rules and still make people feel uncomfortable or alienate them with offensive/sexist comments, that shouldn't be acceptable either. Where's our code of conduct?

(Should probably move that convo here: https://github.com/foundersandcoders/charter/issues/20)

**Comment by sofer** [comment]
+1 to every sentiment expressed here (if that doesn't sound too contradictory). Very pleased that this is getting your collective attention and I groan a bit whenever I re-read the first draft that is still sitting on master.

**Comment by mk4111** [comment]
I agree with @msmichellegar and @minaorangina too in that I don't think the tone of the message is too representative of what FAC stands for either... 

Although rewording might help quite significantly, I also feel that it might just be really difficult to convey the message with its true meanings just by text. Would it be strange to instead have an embedded introductory/explanatory video clip of @sofer talking about the foundations upon which FAC was founded? Just a suggestion, but his FAC supervibe would definitely help.
