### ISSUE TITLE
'Will FAC help me find work?' - More detail would be appreciated

### ISSUE THREAD

**Issue by NataliaLKB** [foundersandcoders/charter#2]
It is great if FAC could start providing more mentorship and help to people who are job hunting, it would be useful to have more detail in this section of what this would entail.

Also, any more thought in partnering up with existing recruiters?

**Comment by NataliaLKB** [comment]
Rereading this sentence: 

_"members will need to act as their own recruiters"_

I know why FAC wants to set up these membership rules, however I can't help but think it makes no sense for Founders & Coders to take a recruiters fee from an employer when they aren't acting as the recruiter. Just my thoughts on the matter, but I am not sure that this is a reasonable ask.

**Comment by sofer** [comment]
@NataliaLKB just to clarify: in principle you think it's asking too much for FAC to expect members to use their own job hunting as an opportunity for FAC to generate income from their prospective employer.

I think it's an interesting debate to be had. What do other people think?

**Comment by iteles** [comment]
I think that the whole 'FAC finding people work' thing is a conversation that needs to be had **once a decision has been made on the employment proposal** as they're inextricably linked and it's counter-productive to discuss one without the other (particularly because what has been requested is that this function of finding people work is undertaken by the new commercial organisation rather than FAC the school).

**Comment by NataliaLKB** [comment]
@iteles that makes sense. Lets hold off this debate until then.

**Comment by sofer** [comment]
@iteles @NataliaLKB agreed.

**Comment by nelsonic** [comment]
@NataliaLKB what _we_ are [_proposing_](https://github.com/nelsonic/ateam) is giving people a _framework_ in which to focus their job hunting. We hope to remove the _overwhelm_ and help people focus on finding a place where they will _love_ working. As an individual its _difficult_ to _negotiate_ terms when apply for jobs, we can _help_ with that.

Simple things like CV review, interview coaching, technical question prep and recommendations to employers will be a good _start_, but we can offer _way_ more through ongoing coaching/mentoring to help people not get _stuck_ working somewhere they don't _enjoy_.

**Comment by NataliaLKB** [comment]
I am completely pro FAC/DWYL coaching people and helping them find employment that they enjoy.

Lets continue this conversation after the vote :smile: .
