### ISSUE TITLE
"To make all other members, as well as members of the public, feel welcome in our space."

### ISSUE THREAD

**Issue by msmichellegar** [foundersandcoders/charter#20]
I love this line, and I'd love to hear more about this. This charter is more based around financial contributions to the space, but where do we set our expectations for members' behaviour? Do we have a code of conduct somewhere?

**Comment by iteles** [comment]
We made a start [here](https://github.com/foundersandcoders/playbook/blob/master/house-rules.md) and then this repo just never go read by anyone...

**Comment by msmichellegar** [comment]
Ah yes I remember looking at that. Those are house rules, I was thinking more like a code of conduct?
