### ISSUE TITLE
Will FAC help me find work quickly?

### ISSUE THREAD

**Issue by izaakrogan** [foundersandcoders/charter#23]
~~FAC will try to support you in your job hunt and mentor you through interviews, but we do not currently have the resources to hire a dedicated recruiter. As we build up a network of partner companies and agency relationships, active recruitment for recent graduates may become less of an issue, but in the short term graduates may have less support than we would like.~~

We are building an awesome recruitment company that will be entirely capable of finding you a great job...

**Comment by msmichellegar** [comment]
I think it's good to be accurate. All of these statements are true. Why not add your sentence as a follow-up.
