### ISSUE TITLE
Time contributions to FAC

### ISSUE THREAD

**Issue by jackpandas** [foundersandcoders/charter#3]
As it stands, I'd like to remain a member of FAC, but I'd only be in the space 1-2 days per week. If I was expected to contribute 20 hours per month to help out with FAC courses, that would mean spending roughly 50% or more of my time in the space helping out. The 20 hour per month benchmark seems pitched such that full timers at FAC are expected to help out for roughly an hour per working day.

Two suggestions:
A) "Members are expected to contribute one hour a day to helping out with FAC
B) Part-timers like me are expected to help out for 7-10 hours a month (would still be higher than A, but perhaps easier to keep an eye on)
C) FAC doesn't need part-time members (I promise not to take this option personally, space is tight!)

**Comment by sofer** [comment]
@jackpandas the FAQ says _"If you are not working full-time on a project from which FAC is benefiting financially and you are using FAC workspace for your own learning or work, then a minimum of 20 hours per month is expected."_. This is badly worded. It might be better to say something like _"members are expected to contribute one hour of support to FAC programmes for every day that they are working in the co-working space on their own projects."_ 

Is that better?

**Comment by sofer** [comment]
@jackpandas I have a pull request. Could you check and merge.

**Comment by jackpandas** [comment]
@sofer Done!
