### ISSUE TITLE
Relocate this document and close the repo

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/charter#31]
As @shiryz has pointed out, programme repos are private, so prospective students can't see documents that live there. However, I'm not sure it makes sense for the `charter` repo to contain a single document.

Would it make more sense for the student commitment(s) to live in the `master-reference`? If so, we can create a folder with the versions for London and Nazareth.

**Comment by rebeccaradding** [comment]
@yvonne-liu does our application still link to this repo or do you paste the student agreement text in?

**Comment by yvonne-liu** [comment]
Happy for this to be moved.

**Comment by rebeccaradding** [comment]
@yvonne-liu to the `master-reference` or to `london-programme`?

**Comment by sofer** [comment]
@rebeccaradding not 100% sure we want to move it. It doesn't really belong in master-reference and if it's in london-programme it won't be visible to the world.

**Comment by rebeccaradding** [comment]
@sofer that's why I asked Yvonne if the application contains a link to this repo or a copy of the document. It might make more sense for it to be a read-only Google document that can be sent to prospective students, which we can link to from any repo. Just not sure it needs to be in a stand-alone repository.

**Comment by sofer** [comment]
@rebeccaradding I am in favour of keeping it here for now. I see Google docs as good for collaborating on editing documents, but GitHub is still a good environment for publishing important information.
