### ISSUE TITLE
Upfront deposits for membership.

### ISSUE THREAD

**Issue by joshpitzalis** [foundersandcoders/charter#4]
As it is currently worded, the charter is largely written for people who live in London and are looking for jobs after they finish the programme. As an international member who is more focused on freelance work, it was a bit confusing till I got to the end of the FAQ.

Perhaps we could structure it so that it directed equally toward people looking for employment, people who intend to freelance, and people who have no intention of finding work (or are employed in another industry), both in the UK and outside.

Below is one way we could restructure the charter to accommodate the range of people mentioned above. 
### 
# Membership

Founders & Coders (FAC) is a not-for-profit company that provides web development training programmes for the public. 

Becoming a member of FAC entails giving back a minimum of twenty hours a month after you complete your programme.

These twenty hours can be spent:
- Support new members in the programme following yours.
- Support an existing meetup group.
- Creating a new meetup group.
- Helping students on our online chatroom.
- Working on paid FAC projects.
- Working with a position that was brokered by FAC.

None of these rules will apply retrospectively.

Followed by the FAQ...
### 

If this makes sense then my questions are:
## How long do I have to continue contributing twenty hours?

As @jackpandas pointed out,  twenty hours a month is one day a week. How long are we expecting people to continue doing this if I they are not working on FAC projects or in FAC brokered positions? @sofer 's response to @jackpandas suggests that this charter only applies to people working in the space. If that is the case, I don't see why international members should not have to contribute.
## What happens if I cancel?

The charter said we can cancel anytime. I don't understand. What's the point of creating a charter if I can just opt out of it?

One possible solution to both of my questions would be to take an upfront deposit for membership. Once you put a decided amount of hours back into the programme, in whichever way you choose, you get your deposit back. For the sake of clarity, let's say 1000 pounds and 100 hours as an arbitrary amount.

This makes the charter clearer, for FAC and prospective students. It also protects FAC from moochers without disturbing the non-profit nature of the programme.

**Comment by sofer** [comment]
@joshpitzalis To make it clear, the 20 hours/month (or 1 hour/day) is only intended to be for people who are occupying our co-working space. It is intended as a form of payment in kind for using the space--which FAC pays for.

**Comment by joshpitzalis** [comment]
I understand now. That was confusing because when I left I thought people just paid rent for using the space. 

Surely the charter should apply to everyone who goes through the program though. There is no reason this cannot apply to everyone. As long as there are listed way to contribute that don't involve being physically present in the space.

**Comment by NataliaLKB** [comment]
:+1: for a list of ways people can contribute who are not in the space.
