### ISSUE TITLE
Why is this charter even necessary?

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/charter#5]
This is the meta-question that I forgot to add to the FAQ and may not be self-evident to everyone reading it. So here we go.

In many ways, FAC has been the most extraordinary success and has demonstrated that it is possible to create a learning environment of real value that is a serious alternative to existing forms of education and training.

In other ways, we are a very long way from success. 

Firstly, we have not yet been able to effectively extend our activities to provide free and stimulating learning environments to those most in need of them. To do so in any serious way will need more resources than we currently have.

Secondly, FAC continues to survive on the unsustainable volunteer labour of me, Ines and Nelson. Unless we solve the problem of how to pay the people without whom the organisation would collapse, we will continue in an almost permanent state of crisis. 

A significant part of the solution to this nascent crisis is likely to lie with Nelson and Ines' [proposal](https://github.com/nelsonic/ateam).

But if FAC wants to survive as a membership-based organisation, where the members have a significant role in the running of the organisation, then my own view is that we are going to need a more serious and longer-term engagement from those of our graduates who wish to remain members. There is something of [a tragedy of the commons](https://en.wikipedia.org/wiki/Tragedy_of_the_commons) at FAC where some (not all!) people happily come to graze here for a few months and then head off without making any serious attempt to replenish the soil.

I don't think this is deliberate and our students are often in a financially and vocationally vulnerable position when they graduate. They are likely to have other and more pressing concerns. 

So, a very clear rules-based approach to membership will allow members to give back to the community in ways that are clear and about which they do not have to think too hard, but which will ensure our survival and the creation of the kinds of surpluses that will allow us to create some real social good that goes beyond the all-too-narrow demographic of our current alumni body.

**Comment by harrygfox** [comment]
+1
