### ISSUE TITLE
Members and community? 

### ISSUE THREAD

**Issue by jackpandas** [foundersandcoders/charter#8]
I think it would probably be good to differentiate between FAC members (people working at FAC, using FAC resources, or in any way using resources that could otherwise be put to use elsewhere) and the FAC community (people who have passed through the FAC foundation). I think there are plenty of people who consider themselves part of the FAC community who no longer work at the FAC location, or have full time jobs, but who still care about FAC as an entity and would probably help out here and there. An issue with defining membership is that these people might feel shut out from FAC and the space, which would be a shame. Therefore perhaps adding a line at the top of the FAQ to indicate that membership is intended to be the rules for community members wishing to base themselves at FAC?

**Comment by sofer** [comment]
@jackpandas I tried to couch the wording in terms that wouldn't exclude anyone who wants to stay involved. Membership is not just for people who stay in the space.
