### ISSUE TITLE
What is a FAC member?

### ISSUE THREAD

**Issue by iteles** [foundersandcoders/charter#9]
I still don't really understand what a FAC member is. 

To me, this document basically says, if you've been through FAC the course, you're expected to either teach the next cohort or give back to FAC in some other way (i.e. a commission when you find paid employment). But I don't really know whether that is entirely related to membership, it's very school-specific.

We just need more context!

**Comment by NataliaLKB** [comment]
I think this is a crucial question to answer, as after reading this charter (which I think is a great idea by the way!) I feel even more confused. 

Also, is it to teach the next cohort or allow FAC to receive money through recruitment fees
_or_ do both of those things to be a member?

**Comment by sofer** [comment]
@NataliaLKB you must excuse me for eliding the two aims. I am deeply frustrated by our current inability to capture value from recruitment, but I think this is a short-term and soluble problem. In the longer-term, commitment to getting involved in other people's learning is more important. Maybe separating the two issues would be helpful.

**Comment by NataliaLKB** [comment]
I would agree to separate the two issues.

As for the concern about recruitment fees, that seems to need an in depth conversation about _why_ FAC hasn't been able to get more value from recruitment.

**Comment by sofer** [comment]
@NataliaLKB @iteles thank you for raising this. 

I suspect that not only am I confusing these two issues, but that what I am calling a _members' charter_ might better be thought of as a _graduates' charter_, i.e. what we expect from anyone who accepts a place on the programme. 

I would be in favour of renaming this document, if others agreed.
